### ISSUE TITLE
Lock-Down Dataset/Resource Creation

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-tsbsatellites#63]
Add the config options (`ckan.auth.create_dataset_if_not_in_organization` etc) to make the Satellites sites (staging + production) require org-membership before a dataset can be created.

**Comment by adamamyl** [comment]
@amercader this shouldn't have any implications on the harvesting, should it?

**Comment by amercader** [comment]
@adamamyl from the auth perspective there won't be any problems, the harvesting uses an internal sysadmin user.

The only issue might be if the original metadata does not have an organization associated. The harvesting will currently still create the dataset without org, but we could easily make it stop if no org is defined:

https://github.com/okfn/ckanext-tsbsatellites/blob/master/ckanext/tsbsatellites/plugin.py#L202

**Comment by adamamyl** [comment]
[clarified] All harvested data sets should have an organisation.

Is my skim of https://github.com/okfn/ckanext-tsbsatellites/blob/master/ckanext/tsbsatellites/plugin.py#L226-L228 correct in thinking that we create an org if it doesn't exist on harvest?

**Comment by amercader** [comment]
Yes. If the harvested document has an org defined the generated dataset gets the org assigned, creating it if necessary. So if the harvested data always has orgs we are good.

**Comment by adamamyl** [comment]
Great! Thanks for clarifying.

**Comment by amercader** [comment]
Set the following in staging and production:

```
ckan.auth.create_unowned_dataset = false
ckan.auth.create_dataset_if_not_in_organization = false
```

For good measure I added a check in a0e68e7 to abort the import during harvesting if the remote metadata does not have an org (which should never happen).

**Comment by adamamyl** [comment]
brilliant, thanks!
